name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: idpx
  IMAGE_NAME: idpx-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Read project name from angular.json
        id: project
        run: |
          echo "PROJECT_NAME=$(jq -r '.projects | keys[0]' angular.json)" >> $GITHUB_ENV

      - name: Log project name
        run: echo "Project name is $PROJECT_NAME"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg PROJECT_NAME=$PROJECT_NAME \
            -t $DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Push Docker Image
        run: docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
